version: '3.1'

services:


  kernel_svd:
    image: ${CI_REGISTRY_IMAGE:-kernel_svd_prod}:${CI_COMMIT_REF_SLUG:-master}
    container_name: kernel_svd_test
    build:
      context: .
      dockerfile: prod.Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    # volumes:
    #   - .:/app/
    ports:
      - "8000:8000"
