
s3:
  AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
  AWS_DEFAULT_REGION: ${S3_DEFAULT_REGION}
  AWS_S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}

mlflow:
  #MLFLOW_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
  #MFLOW_SECRET_ACCESS_KEY: ${S3_ACCESS_KEY_ID}
  MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
  MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
  


